country_iso_dict = {
 'Afghanistan': 'AFG',
 'Åland Islands': 'ALA',
 'Albania': 'ALB',
 'Algeria': 'DZA',
 'American Samoa': 'ASM',
 'Andorra': 'AND',
 'Angola': 'AGO',
 'Anguilla': 'AIA',
 'Antarctica': 'ATA',
 'Antigua and Barbuda': 'ATG',
 'Argentina': 'ARG',
 'Armenia': 'ARM',
 'Aruba': 'ABW',
 'Australia': 'AUS',
 'Austria': 'AUT',
 'Azerbaijan': 'AZE',
 'Bahamas': 'BHS',
 'Bahrain': 'BHR',
 'Bangladesh': 'BGD',
 'Barbados': 'BRB',
 'Belarus': 'BLR',
 'Belgium': 'BEL',
 'Belize': 'BLZ',
 'Benin': 'BEN',
 'Bermuda': 'BMU',
 'Bhutan': 'BTN',
 'Bolivia (Plurinational State of)': 'BOL',
 'Bonaire, Sint Eustatius and Saba': 'BES',
 'Bosnia and Herzegovina': 'BIH',
 'Botswana': 'BWA',
 'Bouvet Island': 'BVT',
 'Brazil': 'BRA',
 'British Indian Ocean Territory': 'IOT',
 'United States Minor Outlying Islands': 'UMI',
 'Virgin Islands (British)': 'VGB',
 'Virgin Islands (U.S.)': 'VIR',
 'Brunei Darussalam': 'BRN',
 'Bulgaria': 'BGR',
 'Burkina Faso': 'BFA',
 'Burundi': 'BDI',
 'Cambodia': 'KHM',
 'Cameroon': 'CMR',
 'Canada': 'CAN',
 'Cabo Verde': 'CPV',
 'Cayman Islands': 'CYM',
 'Central African Republic': 'CAF',
 'Chad': 'TCD',
 'Chile': 'CHL',
 'China': 'CHN',
 'Christmas Island': 'CXR',
 'Cocos (Keeling) Islands': 'CCK',
 'Colombia': 'COL',
 'Comoros': 'COM',
 'Congo': 'COG',
 'Congo (Democratic Republic of the)': 'COD',
 'Cook Islands': 'COK',
 'Costa Rica': 'CRI',
 'Croatia': 'HRV',
 'Cuba': 'CUB',
 'Curaçao': 'CUW',
 'Cyprus': 'CYP',
 'Czech Republic': 'CZE',
 'Denmark': 'DNK',
 'Djibouti': 'DJI',
 'Dominica': 'DMA',
 'Dominican Republic': 'DOM',
 'Ecuador': 'ECU',
 'Egypt': 'EGY',
 'El Salvador': 'SLV',
 'Equatorial Guinea': 'GNQ',
 'Eritrea': 'ERI',
 'Estonia': 'EST',
 'Eswatini': 'SWZ',
 'Ethiopia': 'ETH',
 'Falkland Islands (Malvinas)': 'FLK',
 'Faroe Islands': 'FRO',
 'Fiji': 'FJI',
 'Finland': 'FIN',
 'France': 'FRA',
 'French Guiana': 'GUF',
 'French Polynesia': 'PYF',
 'French Southern Territories': 'ATF',
 'Gabon': 'GAB',
 'Gambia': 'GMB',
 'Georgia': 'GEO',
 'Germany': 'DEU',
 'Ghana': 'GHA',
 'Gibraltar': 'GIB',
 'Greece': 'GRC',
 'Greenland': 'GRL',
 'Grenada': 'GRD',
 'Guadeloupe': 'GLP',
 'Guam': 'GUM',
 'Guatemala': 'GTM',
 'Guernsey': 'GGY',
 'Guinea': 'GIN',
 'Guinea-Bissau': 'GNB',
 'Guyana': 'GUY',
 'Haiti': 'HTI',
 'Heard Island and McDonald Islands': 'HMD',
 'Holy See': 'VAT',
 'Honduras': 'HND',
 'Hong Kong': 'HKG',
 'Hungary': 'HUN',
 'Iceland': 'ISL',
 'India': 'IND',
 'Indonesia': 'IDN',
 'Côte d\'Ivoire': 'CIV',
 'Iran (Islamic Republic of)': 'IRN',
 'Iraq': 'IRQ',
 'Ireland': 'IRL',
 'Isle of Man': 'IMN',
 'Israel': 'ISR',
 'Italy': 'ITA',
 'Jamaica': 'JAM',
 'Japan': 'JPN',
 'Jersey': 'JEY',
 'Jordan': 'JOR',
 'Kazakhstan': 'KAZ',
 'Kenya': 'KEN',
 'Kiribati': 'KIR',
 'Kuwait': 'KWT',
 'Kyrgyzstan': 'KGZ',
 'Lao People\'s Democratic Republic': 'LAO',
 'Latvia': 'LVA',
 'Lebanon': 'LBN',
 'Lesotho': 'LSO',
 'Liberia': 'LBR',
 'Libya': 'LBY',
 'Liechtenstein': 'LIE',
 'Lithuania': 'LTU',
 'Luxembourg': 'LUX',
 'Macao': 'MAC',
 'Madagascar': 'MDG',
 'Malawi': 'MWI',
 'Malaysia': 'MYS',
 'Maldives': 'MDV',
 'Mali': 'MLI',
 'Malta': 'MLT',
 'Marshall Islands': 'MHL',
 'Martinique': 'MTQ',
 'Mauritania': 'MRT',
 'Mauritius': 'MUS',
 'Mayotte': 'MYT',
 'Mexico': 'MEX',
 'Micronesia (Federated States of)': 'FSM',
 'Moldova (Republic of)': 'MDA',
 'Monaco': 'MCO',
 'Mongolia': 'MNG',
 'Montenegro': 'MNE',
 'Montserrat': 'MSR',
 'Morocco': 'MAR',
 'Mozambique': 'MOZ',
 'Myanmar': 'MMR',
 'Namibia': 'NAM',
 'Nauru': 'NRU',
 'Nepal': 'NPL',
 'Netherlands': 'NLD',
 'New Caledonia': 'NCL',
 'New Zealand': 'NZL',
 'Nicaragua': 'NIC',
 'Niger': 'NER',
 'Nigeria': 'NGA',
 'Niue': 'NIU',
 'Norfolk Island': 'NFK',
 'Korea (Democratic People\'s Republic of)': 'PRK',
 'North Macedonia': 'MKD',
 'Northern Mariana Islands': 'MNP',
 'Norway': 'NOR',
 'Oman': 'OMN',
 'Pakistan': 'PAK',
 'Palau': 'PLW',
 'Palestine, State of': 'PSE',
 'Panama': 'PAN',
 'Papua New Guinea': 'PNG',
 'Paraguay': 'PRY',
 'Peru': 'PER',
 'Philippines': 'PHL',
 'Pitcairn': 'PCN',
 'Poland': 'POL',
 'Portugal': 'PRT',
 'Puerto Rico': 'PRI',
 'Qatar': 'QAT',
 'Republic of Kosovo': 'KOS',
 'Réunion': 'REU',
 'Romania': 'ROU',
 'Russian Federation': 'RUS',
 'Rwanda': 'RWA',
 'Saint Barthélemy': 'BLM',
 'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
 'Saint Kitts and Nevis': 'KNA',
 'Saint Lucia': 'LCA',
 'Saint Martin (French part)': 'MAF',
 'Saint Pierre and Miquelon': 'SPM',
 'Saint Vincent and the Grenadines': 'VCT',
 'Samoa': 'WSM',
 'San Marino': 'SMR',
 'Sao Tome and Principe': 'STP',
 'Saudi Arabia': 'SAU',
 'Senegal': 'SEN',
 'Serbia': 'SRB',
 'Seychelles': 'SYC',
 'Sierra Leone': 'SLE',
 'Singapore': 'SGP',
 'Sint Maarten (Dutch part)': 'SXM',
 'Slovakia': 'SVK',
 'Slovenia': 'SVN',
 'Solomon Islands': 'SLB',
 'Somalia': 'SOM',
 'South Africa': 'ZAF',
 'South Georgia and the South Sandwich Islands': 'SGS',
 'Korea (Republic of)': 'KOR',
 'South Sudan': 'SSD',
 'Spain': 'ESP',
 'Sri Lanka': 'LKA',
 'Sudan': 'SDN',
 'Suriname': 'SUR',
 'Svalbard and Jan Mayen': 'SJM',
 'Sweden': 'SWE',
 'Switzerland': 'CHE',
 'Syrian Arab Republic': 'SYR',
 'Taiwan, Province of China[a]': 'TWN',
 'Tajikistan': 'TJK',
 'Tanzania, United Republic of': 'TZA',
 'Thailand': 'THA',
 'Timor-Leste': 'TLS',
 'Togo': 'TGO',
 'Tokelau': 'TKL',
 'Tonga': 'TON',
 'Trinidad and Tobago': 'TTO',
 'Tunisia': 'TUN',
 'Turkey': 'TUR',
 'Turkmenistan': 'TKM',
 'Turks and Caicos Islands': 'TCA',
 'Tuvalu': 'TUV',
 'Uganda': 'UGA',
 'Ukraine': 'UKR',
 'United Arab Emirates': 'ARE',
 'United Kingdom of Great Britain and Northern Ireland': 'GBR',
 'United States of America': 'USA',
 'Uruguay': 'URY',
 'Uzbekistan': 'UZB',
 'Vanuatu': 'VUT',
 'Venezuela (Bolivarian Republic of)': 'VEN',
 'Viet Nam': 'VNM',
 'Wallis and Futuna': 'WLF',
 'Western Sahara': 'ESH',
 'Yemen': 'YEM',
 'Zambia': 'ZMB',
 'Zimbabwe': 'ZWE'
}


country_iso_dict_ger = {
 'Afghanistan': 'AFG',
 'Åland': 'ALA',
 'Albanien': 'ALB',
 'Algerien': 'DZA',
 'Amerikanisch-Samoa': 'ASM',
 'Andorra': 'AND',
 'Angola': 'AGO',
 'Anguilla': 'AIA',
 'Antarktis': 'ATA',
 'Antigua und Barbuda': 'ATG',
 'Argentinien': 'ARG',
 'Armenien': 'ARM',
 'Aruba': 'ABW',
 'Australien': 'AUS',
 'Österreich': 'AUT',
 'Aserbaidschan': 'AZE',
 'Bahamas': 'BHS',
 'Bahrain': 'BHR',
 'Bangladesch': 'BGD',
 'Barbados': 'BRB',
 'Weißrussland': 'BLR',
 'Belgien': 'BEL',
 'Belize': 'BLZ',
 'Benin': 'BEN',
 'Bermuda': 'BMU',
 'Bhutan': 'BTN',
 'Bolivien': 'BOL',
 'Bonaire, Sint Eustatius und Saba': 'BES',
 'Bosnien und Herzegowina': 'BIH',
 'Botswana': 'BWA',
 'Bouvetinsel': 'BVT',
 'Brasilien': 'BRA',
 'Britisches Territorium im Indischen Ozean': 'IOT',
 'Kleinere Inselbesitzungen der Vereinigten Staaten': 'UMI',
 'Britische Jungferninseln': 'VGB',
 'Amerikanische Jungferninseln': 'VIR',
 'Brunei Darussalam': 'BRN',
 'Bulgarien': 'BGR',
 'Burkina Faso': 'BFA',
 'Burundi': 'BDI',
 'Kambodscha': 'KHM',
 'Kamerun': 'CMR',
 'Kanada': 'CAN',
 'Kap Verde': 'CPV',
 'Kaimaninseln': 'CYM',
 'Zentralafrikanische Republik': 'CAF',
 'Tschad': 'TCD',
 'Chile': 'CHL',
 'China': 'CHN',
 'Weihnachtsinsel': 'CXR',
 'Kokosinseln': 'CCK',
 'Kolumbien': 'COL',
 'Komoren': 'COM',
 'Kongo': 'COG',
 'Demokratische Republik Kongo': 'COD',
 'Cookinseln': 'COK',
 'Costa Rica': 'CRI',
 'Kroatien': 'HRV',
 'Kuba': 'CUB',
 'Curaçao': 'CUW',
 'Zypern': 'CYP',
 'Tschechien': 'CZE',
 'Dänemark': 'DNK',
 'Dschibuti': 'DJI',
 'Dominica': 'DMA',
 'Dominikanische Republik': 'DOM',
 'Ecuador': 'ECU',
 'Ägypten': 'EGY',
 'El Salvador': 'SLV',
 'Äquatorialguinea': 'GNQ',
 'Eritrea': 'ERI',
 'Estland': 'EST',
 'Eswatini': 'SWZ',
 'Äthiopien': 'ETH',
 'Falklandinseln': 'FLK',
 'Färöer': 'FRO',
 'Fidschi': 'FJI',
 'Finnland': 'FIN',
 'Frankreich': 'FRA',
 'Französisch-Guayana': 'GUF',
 'Französisch-Polynesien': 'PYF',
 'Französische Süd- und Antarktisgebiete': 'ATF',
 'Gabun': 'GAB',
 'Gambia': 'GMB',
 'Georgien': 'GEO',
 'Deutschland': 'DEU',
 'Ghana': 'GHA',
 'Gibraltar': 'GIB',
 'Griechenland': 'GRC',
 'Grönland': 'GRL',
 'Grenada': 'GRD',
 'Guadeloupe': 'GLP',
 'Guam': 'GUM',
 'Guatemala': 'GTM',
 'Guernsey': 'GGY',
 'Guinea': 'GIN',
 'Guinea-Bissau': 'GNB',
 'Guyana': 'GUY',
 'Haiti': 'HTI',
 'Heard und McDonaldinseln': 'HMD',
 'Heiliger Stuhl': 'VAT',
 'Honduras': 'HND',
 'Hongkong': 'HKG',
 'Ungarn': 'HUN',
 'Island': 'ISL',
 'Indien': 'IND',
 'Indonesien': 'IDN',
 'Elfenbeinküste': 'CIV',
 'Iran': 'IRN',
 'Irak': 'IRQ',
 'Irland': 'IRL',
 'Isle of Man': 'IMN',
 'Israel': 'ISR',
 'Italien': 'ITA',
 'Jamaika': 'JAM',
 'Japan': 'JPN',
 'Jersey': 'JEY',
 'Jordanien': 'JOR',
 'Kasachstan': 'KAZ',
 'Kenia': 'KEN',
 'Kiribati': 'KIR',
 'Kuwait': 'KWT',
 'Kirgisistan': 'KGZ',
 'Laos': 'LAO',
 'Lettland': 'LVA',
 'Libanon': 'LBN',
 'Lesotho': 'LSO',
 'Liberia': 'LBR',
 'Libyen': 'LBY',
 'Liechtenstein': 'LIE',
 'Litauen': 'LTU',
 'Luxemburg': 'LUX',
 'Macao': 'MAC',
 'Madagaskar': 'MDG',
 'Malawi': 'MWI',
 'Malaysia': 'MYS',
 'Malediven': 'MDV',
 'Mali': 'MLI',
 'Malta': 'MLT',
 'Marshallinseln': 'MHL',
 'Martinique': 'MTQ',
 'Mauretanien': 'MRT',
 'Mauritius': 'MUS',
 'Mayotte': 'MYT',
 'Mexiko': 'MEX',
 'Mikronesien': 'FSM',
 'Moldau': 'MDA',
 'Monaco': 'MCO',
 'Mongolei': 'MNG',
 'Montenegro': 'MNE',
 'Montserrat': 'MSR',
 'Marokko': 'MAR',
 'Mosambik': 'MOZ',
 'Myanmar': 'MMR',
 'Namibia': 'NAM',
 'Nauru': 'NRU',
 'Nepal': 'NPL',
 'Niederlande': 'NLD',
 'Neukaledonien': 'NCL',
 'Neuseeland': 'NZL',
 'Nicaragua': 'NIC',
 'Niger': 'NER',
 'Nigeria': 'NGA',
 'Niue': 'NIU',
 'Norfolkinsel': 'NFK',
 'Nordkorea': 'PRK',
 'Nordmazedonien': 'MKD',
 'Nördliche Marianen': 'MNP',
 'Norwegen': 'NOR',
 'Oman': 'OMN',
 'Pakistan': 'PAK',
 'Palau': 'PLW',
 'Palästina': 'PSE',
 'Panama': 'PAN',
 'Papua-Neuguinea': 'PNG',
 'Paraguay': 'PRY',
 'Peru': 'PER',
 'Philippinen': 'PHL',
 'Pitcairninseln': 'PCN',
 'Polen': 'POL',
 'Portugal': 'PRT',
 'Puerto Rico': 'PRI',
 'Katar': 'QAT',
 'Kosovo': 'KOS',
 'Réunion': 'REU',
 'Rumänien': 'ROU',
 'Russland': 'RUS',
 'Ruanda': 'RWA',
 'St. Barthélemy': 'BLM',
 'St. Helena': 'SHN',
 'St. Kitts und Nevis': 'KNA',
 'St. Lucia': 'LCA',
 'St. Martin': 'MAF',
 'St. Pierre und Miquelon': 'SPM',
 'St. Vincent und die Grenadinen': 'VCT',
 'Samoa': 'WSM',
 'San Marino': 'SMR',
 'São Tomé und Príncipe': 'STP',
 'Saudi-Arabien': 'SAU',
 'Senegal': 'SEN',
 'Serbien': 'SRB',
 'Seychellen': 'SYC',
 'Sierra Leone': 'SLE',
 'Singapur': 'SGP',
 'Sint Maarten': 'SXM',
 'Slowakei': 'SVK',
 'Slowenien': 'SVN',
 'Salomonen': 'SLB',
 'Somalia': 'SOM',
 'Südafrika': 'ZAF',
 'Südgeorgien und die Südlichen Sandwichinseln': 'SGS',
 'Südkorea': 'KOR',
 'Südsudan': 'SSD',
 'Spanien': 'ESP',
 'Sri Lanka': 'LKA',
 'Sudan': 'SDN',
 'Suriname': 'SUR',
 'Svalbard und Jan Mayen': 'SJM',
 'Schweden': 'SWE',
 'Schweiz': 'CHE',
 'Syrien': 'SYR',
 'Taiwan': 'TWN',
 'Tadschikistan': 'TJK',
 'Tansania': 'TZA',
 'Thailand': 'THA',
 'Timor-Leste': 'TLS',
 'Togo': 'TGO',
 'Tokelau': 'TKL',
 'Tonga': 'TON',
 'Trinidad und Tobago': 'TTO',
 'Tunesien': 'TUN',
 'Türkei': 'TUR',
 'Turkmenistan': 'TKM',
 'Turks- und Caicosinseln': 'TCA',
 'Tuvalu': 'TUV',
 'Uganda': 'UGA',
 'Ukraine': 'UKR',
 'Vereinigte Arabische Emirate': 'ARE',
 'Vereinigtes Königreich': 'GBR',
 'USA': 'USA',
 'Uruguay': 'URY',
 'Usbekistan': 'UZB',
 'Vanuatu': 'VUT',
 'Venezuela': 'VEN',
 'Vietnam': 'VNM',
 'Wallis und Futuna': 'WLF',
 'Westsahara': 'ESH',
 'Jemen': 'YEM',
 'Sambia': 'ZMB',
 'Simbabwe': 'ZWE'
}

# pycountry-Bibliothek


list_off = ['AFG', 'ALB', 'DZA', 'AND', 'AGO', 'ATG',
            'ARG', 'ARM', 'AUS', 'AUT', 'AZE', 'BHS',
            'BHR', 'BGD', 'BRB', 'BLR', 'BEL', 'BLZ',
            'BEN', 'BTN', 'BOL', 'BIH', 'BWA', 'BRA',
            'BRN', 'BGR', 'BFA', 'BDI', 'CPV', 'KHM',
            'CMR', 'CAN', 'CAF', 'TCD', 'CHL', 'CHN',
            'COL', 'COM', 'COG', 'COD', 'CRI', 'CIV',
            'HRV', 'CUB', 'CYP', 'CZE', 'DNK', 'DJI',
            'DMA', 'DOM', 'ECU', 'EGY', 'SLV', 'GNQ',
            'ERI', 'EST', 'SWZ', 'ETH', 'FJI', 'FIN', 
            'FRA', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA',
            'GRC', 'GRD', 'GTM', 'GIN', 'GNB', 'GUY',
            'HTI', 'HND', 'HUN', 'ISL', 'IND', 'IDN',
            'IRN', 'IRQ', 'IRL', 'ISR', 'ITA', 'JAM',
            'JPN', 'JOR', 'KAZ', 'KEN', 'KIR', 'PRK',
            'KOR', 'KWT', 'KGZ', 'LAO', 'LVA', 'LBN',
            'LSO', 'LBR', 'LBY', 'LIE', 'LTU', 'LUX',
            'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT',
            'MHL', 'MRT', 'MUS', 'MEX', 'FSM', 'MDA',
            'MCO', 'MNG', 'MNE', 'MAR', 'MOZ', 'MMR',
            'NAM', 'NRU', 'NPL', 'NLD', 'NZL', 'NIC',
            'NER', 'NGA', 'MKD', 'NOR', 'OMN', 'PAK',
            'PLW', 'PAN', 'PNG', 'PRY', 'PER', 'PHL',
            'POL', 'PRT', 'QAT', 'ROU', 'RUS', 'RWA',
            'KNA', 'LCA', 'VCT', 'WSM', 'SMR', 'STP',
            'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP',
            'SVK', 'SVN', 'SLB', 'SOM', 'ZAF', 'SSD',
            'ESP', 'LKA', 'SDN', 'SUR', 'SWE', 'CHE',
            'SYR', 'TJK', 'TZA', 'THA', 'TLS', 'TGO',
            'TON', 'TTO', 'TUN', 'TUR', 'TKM', 'TUV',
            'UGA', 'UKR', 'ARE', 'GBR', 'USA', 'URY',
            'UZB', 'VUT', 'VEN', 'VNM', 'YEM', 'ZMB',
            'ZWE'
]

regions_dict = {'AFG': 'South Asia',
                'AGO': 'Africa',
                'ALB': 'Europe',
                'AND': 'Europe',
                'ARE': 'Middle East',
                'ARG': 'Americas',
                'ARM': 'Middle East',
                'ATG': 'Americas',
                'AUS': 'Oceania',
                'AUT': 'Europe',
                'AZE': 'Middle East',
                'BDI': 'Africa',
                'BEL': 'Europe',
                'BEN': 'Africa',
                'BFA': 'Africa',
                'BGD': 'South Asia',
                'BGR': 'Europe',
                'BHR': 'Middle East',
                'BHS': 'Americas',
                'BIH': 'Europe',
                'BLR': 'Europe',
                'BLZ': 'Americas',
                'BOL': 'Americas',
                'BRA': 'Americas',
                'BRB': 'Americas',
                'BRN': 'South Asia',
                'BTN': 'South Asia',
                'BWA': 'Africa',
                'CAF': 'Africa',
                'CAN': 'Americas',
                'CHE': 'Europe',
                'CHL': 'Americas',
                'CHN': 'East Asia and the Pacific',
                'CIV': 'Africa',
                'CMR': 'Africa',
                'COD': 'Africa',
                'COG': 'Africa',
                'COL': 'Americas',
                'COM': 'Africa',
                'CPV': 'Africa',
                'CRI': 'Americas',
                'CUB': 'Americas',
                'CYP': 'Middle East',
                'CZE': 'Europe',
                'DEU': 'Europe',
                'DJI': 'Africa',
                'DMA': 'Americas',
                'DNK': 'Europe',
                'DOM': 'Americas',
                'DZA': 'Africa',
                'ECU': 'Americas',
                'EGY': 'Africa',
                'ERI': 'Africa',
                'ESP': 'Europe',
                'EST': 'Europe',
                'ETH': 'Africa',
                'FIN': 'Europe',
                'FJI': 'Oceania',
                'FRA': 'Europe',
                'FSM': 'Oceania',
                'GAB': 'Africa',
                'GBR': 'Europe',
                'GEO': 'Middle East',
                'GHA': 'Africa',
                'GIN': 'Africa',
                'GMB': 'Africa',
                'GNB': 'Africa',
                'GNQ': 'Africa',
                'GRC': 'Europe',
                'GRD': 'Americas',
                'GTM': 'Americas',
                'GUY': 'Americas',
                'HND': 'Americas',
                'HRV': 'Europe',
                'HTI': 'Americas',
                'HUN': 'Europe',
                'IDN': 'South Asia',
                'IND': 'South Asia',
                'IRL': 'Europe',
                'IRN': 'South Asia',
                'IRQ': 'Middle East',
                'ISL': 'Europe',
                'ISR': 'Middle East',
                'ITA': 'Europe',
                'JAM': 'Americas',
                'JOR': 'Middle East',
                'JPN': 'East Asia and the Pacific',
                'KAZ': 'Middle East',
                'KEN': 'Africa',
                'KGZ': 'Middle East',
                'KHM': 'South Asia',
                'KIR': 'Oceania',
                'KNA': 'Americas',
                'KOR': 'East Asia and the Pacific',
                'KWT': 'Middle East',
                'LAO': 'South Asia',
                'LBN': 'Middle East',
                'LBR': 'Africa',
                'LBY': 'Africa',
                'LCA': 'Americas',
                'LIE': 'Europe',
                'LKA': 'South Asia',
                'LSO': 'Africa',
                'LTU': 'Europe',
                'LUX': 'Europe',
                'LVA': 'Europe',
                'MAR': 'Africa',
                'MCO': 'Europe',
                'MDA': 'Europe',
                'MDG': 'Africa',
                'MDV': 'South Asia',
                'MEX': 'Americas',
                'MHL': 'Oceania',
                'MKD': 'Europe',
                'MLI': 'Africa',
                'MLT': 'Europe',
                'MMR': 'South Asia',
                'MNE': 'Europe',
                'MNG': 'East Asia and the Pacific',
                'MOZ': 'Africa',
                'MRT': 'Africa',
                'MUS': 'Africa',
                'MWI': 'Africa',
                'MYS': 'South Asia',
                'NAM': 'Africa',
                'NER': 'Africa',
                'NGA': 'Africa',
                'NIC': 'Americas',
                'NLD': 'Europe',
                'NOR': 'Europe',
                'NPL': 'South Asia',
                'NRU': 'Oceania',
                'NZL': 'Oceania',
                'OMN': 'Middle East',
                'PAK': 'South Asia',
                'PAN': 'Americas',
                'PER': 'Americas',
                'PHL': 'South Asia',
                'PLW': 'Oceania',
                'PNG': 'Oceania',
                'POL': 'Europe',
                'PRK': 'East Asia and the Pacific',
                'PRT': 'Europe',
                'PRY': 'Americas',
                'QAT': 'Middle East',
                'ROU': 'Europe',
                'RUS': 'Europe',
                'RWA': 'Africa',
                'SAU': 'Middle East',
                'SDN': 'Africa',
                'SEN': 'Africa',
                'SGP': 'South Asia',
                'SLB': 'Oceania',
                'SLE': 'Africa',
                'SLV': 'Americas',
                'SMR': 'Europe',
                'SOM': 'Africa',
                'SRB': 'Europe',
                'SSD': 'Africa',
                'STP': 'Africa',
                'SUR': 'Americas',
                'SVK': 'Europe',
                'SVN': 'Europe',
                'SWE': 'Europe',
                'SWZ': 'Africa',
                'SYC': 'Africa',
                'SYR': 'Middle East',
                'TCD': 'Africa',
                'TGO': 'Africa',
                'THA': 'South Asia',
                'TJK': 'Middle East',
                'TKM': 'Middle East',
                'TLS': 'South Asia',
                'TON': 'Oceania',
                'TTO': 'Americas',
                'TUN': 'Africa',
                'TUR': 'Middle East',
                'TUV': 'Oceania',
                'TZA': 'Africa',
                'UGA': 'Africa',
                'UKR': 'Europe',
                'URY': 'Americas',
                'USA': 'Americas',
                'UZB': 'Middle East',
                'VCT': 'Americas',
                'VEN': 'Americas',
                'VNM': 'South Asia',
                'VUT': 'Oceania',
                'WSM': 'Oceania',
                'YEM': 'Middle East',
                'ZAF': 'Africa',
                'ZMB': 'Africa',
                'ZWE': 'Africa'
}