INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('AFG','South Asia'),
	 ('AGO','Africa'),
	 ('ALB','Europe'),
	 ('AND','Europe'),
	 ('ARE','Middle East'),
	 ('ARG','Americas'),
	 ('ARM','Middle East'),
	 ('ATG','Americas'),
	 ('AUS','Oceania'),
	 ('AUT','Europe');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('AZE','Middle East'),
	 ('BDI','Africa'),
	 ('BEL','Europe'),
	 ('BEN','Africa'),
	 ('BFA','Africa'),
	 ('BGD','South Asia'),
	 ('BGR','Europe'),
	 ('BHR','Middle East'),
	 ('BHS','Americas'),
	 ('BIH','Europe');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('BLR','Europe'),
	 ('BLZ','Americas'),
	 ('BOL','Americas'),
	 ('BRA','Americas'),
	 ('BRB','Americas'),
	 ('BRN','South Asia'),
	 ('BTN','South Asia'),
	 ('BWA','Africa'),
	 ('CAF','Africa'),
	 ('CAN','Americas');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('CHE','Europe'),
	 ('CHL','Americas'),
	 ('CHN','East Asia and the Pacific'),
	 ('CIV','Africa'),
	 ('CMR','Africa'),
	 ('COD','Africa'),
	 ('COG','Africa'),
	 ('COL','Americas'),
	 ('COM','Africa'),
	 ('CPV','Africa');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('CRI','Americas'),
	 ('CUB','Americas'),
	 ('CYP','Middle East'),
	 ('CZE','Europe'),
	 ('DEU','Europe'),
	 ('DJI','Africa'),
	 ('DMA','Americas'),
	 ('DNK','Europe'),
	 ('DOM','Americas'),
	 ('DZA','Africa');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('ECU','Americas'),
	 ('EGY','Africa'),
	 ('ERI','Africa'),
	 ('ESP','Europe'),
	 ('EST','Europe'),
	 ('ETH','Africa'),
	 ('FIN','Europe'),
	 ('FJI','Oceania'),
	 ('FRA','Europe'),
	 ('FSM','Oceania');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('GAB','Africa'),
	 ('GBR','Europe'),
	 ('GEO','Middle East'),
	 ('GHA','Africa'),
	 ('GIN','Africa'),
	 ('GMB','Africa'),
	 ('GNB','Africa'),
	 ('GNQ','Africa'),
	 ('GRC','Europe'),
	 ('GRD','Americas');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('GTM','Americas'),
	 ('GUY','Americas'),
	 ('HND','Americas'),
	 ('HRV','Europe'),
	 ('HTI','Americas'),
	 ('HUN','Europe'),
	 ('IDN','South Asia'),
	 ('IND','South Asia'),
	 ('IRL','Europe'),
	 ('IRN','South Asia');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('IRQ','Middle East'),
	 ('ISL','Europe'),
	 ('ISR','Middle East'),
	 ('ITA','Europe'),
	 ('JAM','Americas'),
	 ('JOR','Middle East'),
	 ('JPN','East Asia and the Pacific'),
	 ('KAZ','Middle East'),
	 ('KEN','Africa'),
	 ('KGZ','Middle East');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('KHM','South Asia'),
	 ('KIR','Oceania'),
	 ('KNA','Americas'),
	 ('KOR','East Asia and the Pacific'),
	 ('KWT','Middle East'),
	 ('LAO','South Asia'),
	 ('LBN','Middle East'),
	 ('LBR','Africa'),
	 ('LBY','Africa'),
	 ('LCA','Americas');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('LIE','Europe'),
	 ('LKA','South Asia'),
	 ('LSO','Africa'),
	 ('LTU','Europe'),
	 ('LUX','Europe'),
	 ('LVA','Europe'),
	 ('MAR','Africa'),
	 ('MCO','Europe'),
	 ('MDA','Europe'),
	 ('MDG','Africa');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('MDV','South Asia'),
	 ('MEX','Americas'),
	 ('MHL','Oceania'),
	 ('MKD','Europe'),
	 ('MLI','Africa'),
	 ('MLT','Europe'),
	 ('MMR','South Asia'),
	 ('MNE','Europe'),
	 ('MNG','East Asia and the Pacific'),
	 ('MOZ','Africa');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('MRT','Africa'),
	 ('MUS','Africa'),
	 ('MWI','Africa'),
	 ('MYS','South Asia'),
	 ('NAM','Africa'),
	 ('NER','Africa'),
	 ('NGA','Africa'),
	 ('NIC','Americas'),
	 ('NLD','Europe'),
	 ('NOR','Europe');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('NPL','South Asia'),
	 ('NRU','Oceania'),
	 ('NZL','Oceania'),
	 ('OMN','Middle East'),
	 ('PAK','South Asia'),
	 ('PAN','Americas'),
	 ('PER','Americas'),
	 ('PHL','South Asia'),
	 ('PLW','Oceania'),
	 ('PNG','Oceania');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('POL','Europe'),
	 ('PRK','East Asia and the Pacific'),
	 ('PRT','Europe'),
	 ('PRY','Americas'),
	 ('QAT','Middle East'),
	 ('ROU','Europe'),
	 ('RUS','Europe'),
	 ('RWA','Africa'),
	 ('SAU','Middle East'),
	 ('SDN','Africa');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('SEN','Africa'),
	 ('SGP','South Asia'),
	 ('SLB','Oceania'),
	 ('SLE','Africa'),
	 ('SLV','Americas'),
	 ('SMR','Europe'),
	 ('SOM','Africa'),
	 ('SRB','Europe'),
	 ('SSD','Africa'),
	 ('STP','Africa');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('SUR','Americas'),
	 ('SVK','Europe'),
	 ('SVN','Europe'),
	 ('SWE','Europe'),
	 ('SWZ','Africa'),
	 ('SYC','Africa'),
	 ('SYR','Middle East'),
	 ('TCD','Africa'),
	 ('TGO','Africa'),
	 ('THA','South Asia');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('TJK','Middle East'),
	 ('TKM','Middle East'),
	 ('TLS','South Asia'),
	 ('TON','Oceania'),
	 ('TTO','Americas'),
	 ('TUN','Africa'),
	 ('TUR','Middle East'),
	 ('TUV','Oceania'),
	 ('TZA','Africa'),
	 ('UGA','Africa');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('UKR','Europe'),
	 ('URY','Americas'),
	 ('USA','Americas'),
	 ('UZB','Middle East'),
	 ('VCT','Americas'),
	 ('VEN','Americas'),
	 ('VNM','South Asia'),
	 ('VUT','Oceania'),
	 ('WSM','Oceania'),
	 ('YEM','Middle East');
INSERT INTO capstone_travel_index.world_regions (iso3,"sub-region_name") VALUES
	 ('ZAF','Africa'),
	 ('ZMB','Africa'),
	 ('ZWE','Africa');
